### PR TITLE
update for drain result API change

### PR DESCRIPTION
**Pull request by potash**
I made a small refactor in the drain API a while back: (`Step.get_result()` became simply `Step.result`). This updates the lead model for this change. @geneorama I suspect your model pipeline won't run without merging this.

### CODE REVIEW

**Comment by geneorama** [comment]
Just making a note of the steps to add the remote and check out the model:
```
$ git remote add potash https://github.com/potash/lead-model
$ git fetch potash
$ git checkout potash/issue/result-api
```

**Comment by geneorama** [comment]
I'm re-running drake now that the other fixes are in place, I had forgotten that the dedupe step never ran.  Of course this takes a while, so it's running now.  I'll test the updated drain command tomorrow when the data step is complete.

@tomschenkjr FYI this is the update that I mentioned earlier.  I'm not sure you've seen this.

**Comment by tomschenkjr** [comment]
Gene, are you capturing these steps somewhere (i.e., running dedupe steps)? That is, if I spun-up an AWS instance, would we be able to step through each required step?

**Comment by geneorama** [comment]
There really are no steps to capture beyond what's in the readme, it's just a matter of getting everything installed and all the configuration files right.

The exceptions are all bugs that Eric's fixing or switching over the database configurations (eg not linking to prod when you want dev) and making sure that all the profiles are in sync.

So yes I'm trying to capture anything else that can be a pitfall

**Pull request merged**
