### PR TITLE
v1.0.0-rc.1

### PR DESCRIPTION
**Pull request by tomschenkjr**
Testing has been completed on this commit alongside the development version of the v0.5.0 of the API on the development server. @geneorama, please confirm this by approving this pull request.

This resolves #5 and [lead-prediction-runner#24](https://gitlab.cityofchicago.org/lead-paint-research/lead-API-internal/issues/24). @potash, please confirm accuracy of which issues it closes by approving this pull request.

This will start establishing versioning for this project. ~~I propose v0.9.0. The model is likely to change to [support v0.6.0 of the API](https://github.com/Chicago/lead-safe-api-docs/wiki#roadmap) (e.g., defining how we label the risk score). After this pull request is accepted, we will create a GitHub release and tagging this as `v0.9.0`.~~ _See thread._

### CODE REVIEW

**Review by potash — COMMENTED** [review]
The referenced issues are correct. Regarding versioning, I don't think there will be any changes except bug fixes (#1) and perhaps some helpers to (1) support the validation/calibration on alliance data and (2) improve runner response time.

**Comment by tomschenkjr** [comment]
RE: changes

Do you think we will make changes to support output of the prediction (i.e., odds ratio, risk ratio, risk notes)?

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by potash** [comment]
I'd like to keep most of those changes in the runner repo. The changes here would be minimal so far as I can tell.

**Comment by tomschenkjr** [comment]
I've updated the proposed version number to v1.0.0-rc.1 based on feedback. Please approve if you're OK with the changes.

**Review by potash — APPROVED** [review]

**Comment by tomschenkjr** [comment]
@geneorama - A reminder to approve or provide comments on this.

**Review by geneorama — APPROVED** [review]

**Pull request merged**
